version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"   # HTTP port
      - "8443:8443"   # HTTPS port
    restart: unless-stopped
    environment:
      - PORT=8443      # Primary port for HTTPS
      - HTTP_PORT=8080 # Fallback HTTP port
      - HOST=0.0.0.0
    volumes:
      - ./certs:/certs:ro  # Mount certificates as read-only
    
  # Optional: Add a database service if needed
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: appdb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
