version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
    
  # Optional: Add a database service if needed
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: appdb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
